apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spre-gosys-pdf
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: is_alive
    initialDelay: 5
  readiness:
    path: is_ready
    initialDelay: 5
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /prometheus
