apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spre-gosys-pdf
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  startup:
    path: /internal/is_ready
    initialDelay: 5
    periodSeconds: 2
    failureThreshold: 9
  liveness:
    path: /internal/is_alive
  readiness:
    path: /internal/is_ready
  accessPolicy:
    inbound:
      rules:
        - application: spre-gosys
    outbound:
      rules:
        - application: logging
          namespace: nais-system
  resources:
    limits:
      memory: 2048Mi
    requests:
      cpu: 30m
      memory: 800Mi
  replicas:
    min: 2
    max: 12
    scalingStrategy:
      cpu:
        thresholdPercentage: 800
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
