apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spre-gosys-pdf
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
  readiness:
    path: /internal/is_ready
    initialDelay: 10
  accessPolicy:
    inbound:
      rules:
        - application: spre-gosys
    outbound:
      rules:
        - application: logging
          namespace: nais-system
  resources:
    limits:
      memory: 2048Mi
    requests:
      cpu: 50m
      memory: 64Mi
  replicas:
    min: 2
    max: 12
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
