name: master

on:
  push:
    branches:
      - master

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/docker-build-push@v0
        name: Build and push image
        id: docker-build-push
        with:
          team: tbd
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
  
  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cluster: [dev-gcp, prod-gcp]
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: deploy/${{ matrix.cluster }}.yml
          IMAGE: ${{ needs.build.outputs.image }}
