name: master

on:
  push:
    branches:
      - master

env:
  IMAGENAME: ghcr.io/${{ github.repository }}/spre-gosys-pdf

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Declare outputs
        id: declare
        run: |
          echo "::set-output name=image::${IMAGENAME}:$(echo ${{ github.sha }} | cut -c1-7)"
    outputs:
      image: "${{ steps.declare.outputs.image }}"
  build:
    needs: setup
    runs-on: ubuntu-latest
    env:
      IMAGE: "${{ needs.setup.outputs.image }}"
    steps:
      - uses: actions/checkout@v1
      - name: build docker image
        run: docker build -t ${IMAGE} .
      - name: push docker image
        run: |
          docker login --username "$GITHUB_REPOSITORY" -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
          docker push ${IMAGE}
  deployDev:
    name: Deploy to dev
    needs: [setup, build]
    runs-on: ubuntu-latest
    env:
      IMAGE: "${{ needs.setup.outputs.image }}"
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: deploy/dev.yml

  deployProd:
    name: Deploy to prod
    needs: [setup, build, deployDev]
    runs-on: ubuntu-latest
    env:
      IMAGE: "${{ needs.setup.outputs.image }}"
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: deploy/prod.yml
